[theme]
base = "light"
primaryColor = "#087E8B"
backgroundColor = "#F5F8FA"
secondaryBackgroundColor = "#EDF2F6"
textColor = "#172E40"
font = "sans serif"
borderColor = "#DCE5ED"
baseRadius = "0.75rem"
dataframeHeaderBackgroundColor = "#EDF2F6"

[theme.sidebar]
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6F8"

[server]
maxUploadSize = 5

[browser]
gatherUsageStats = false
